# Copyright 2020 K8s Network Plumbing Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for multus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # -- Repository for the Multus image.
  repository: ghcr.io/k8snetworkplumbingwg/multus-cni
  # -- Tag of the Multus image.
  tag: v4.1.0
  pullPolicy: IfNotPresent

#imagePullSecrets: []
#nameOverride: ""
#fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  #create: true
  # Annotations to add to the service account
  #annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: multus
# -- Resources for the Multus pod.
resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

args:
  # -- The directory where CNI binaries are installed.
  cniBinDir: "/host/opt/cni/bin"
  # -- The directory where CNI configurations are stored.
  cniConfDir: "/host/etc/cni/net.d"
  # -- Version of the CNI to use.
  cniVersion: ""
  # -- The configuration file for Multus.
  multusConfFile: "auto"
  # -- Path to the Multus binary file.
  multusBinFile: "/usr/src/multus-cni/bin/multus"
  # -- Directory for Multus-specific CNI configurations.
  multusCNIConfDir: "/host/etc/cni/multus/net.d"
  # -- Whether to skip copying the Multus binary file.
  skipMultusBinaryCopy: false
  # -- Path to the kubeconfig file for Multus.
  multusKubeConfigFileHost: "/etc/cni/net.d/multus.d/multus.kubeconfig"
  # -- Name of the master CNI file in the Multus auto-configuration directory.
  multusMasterCNIFileName: ""
  # -- Enable namespace isolation.
  namespaceIsolation: false
  # -- Comma-separated list of global namespaces for use with namespace isolation.
  globalNamespaces: ""
  # -- Directory for the Multus auto-configuration.
  multusAutoconfigDir: "/host/etc/cni/net.d"
  # -- Whether to log to stderr.
  multusLogToStderr: true
  # -- Log level for Multus.
  multusLogLevel: ""
  # -- Path to the Multus log file.
  multusLogFile: ""
  # -- Override the network name from the master CNI file.
  overrideNetworkName: false
  # -- Cleanup configuration files on exit.
  cleanupConfigOnExit: false
  # -- Skip watching for configuration changes.
  skipConfigWatch: false
  # -- Rename the master configuration file to invalidate it.
  renameConfFile: false
  # -- File used to indicate readiness.
  readinessIndicatorFile: ""
  # -- Additional directory to include in the CNI binDir option.
  additionalBinDir: ""
  # -- Skip TLS verification.
  skipTLSVerify: false
  # -- Force the use of a specific CNI version.
  forceCNIVersion: false
# -- Node selector for pod assignment.
nodeSelector: {}
# -- Tolerations for pod assignment.
tolerations:
  - operator: Exists
    effect: NoSchedule
# -- securityContext for the pod.
securityContext:
  privileged: true
