# Copyright 2020 K8s Network Plumbing Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

images:
  registry: docker.io
  sriovCni:
    repository: ghcr.io/k8snetworkplumbingwg/sriov-network-device-plugin
    tag: latest
  sriovDevicePlugin:
    repository: nfvpe/sriov-device-plugin
    tag: v3.1
  pullPolicy: IfNotPresent

serviceAccount:
  name: sriov-device-plugin-test


resources:
    requests:
      memory: "50Mi"
      cpu: "100m"
    limits:
      memory: "50Mi"
      cpu: "100m"

securityContext:
  privileged: true

nodeSelector:
  kubernetes.io/arch: amd64

# -- Arguments for the sriov-device-plugin
args:
  - --log-dir=sriovdp
  - --log-level=10

config:
  scMountPaths:
    cnibin: "/host/opt/cni/bin"
  sdpMountPaths:
    deviceSock: "/var/lib/kubelet/device-plugins/"
    log: "/var/log"
    configVolume: "/etc/pcidp/config.json"
  sriov_device_plugin: |
    {
      "resourceList": [
        {
          "resourceName": "intel_sriov_netdevice",
          "selectors": {
            "vendors": [
              "8086"
            ],
            "devices": [
              154c,
              10ed
            ],
            "drivers": [
              "i40evf",
              "ixgbevf"
            ]
          }
        },
        {
          "resourceName": "intel_sriov_dpdk",
          "selectors": {
            "vendors": [
              "8086"
            ],
            "devices": [
              154c,
              10ed
            ],
            "drivers": [
              "vfio-pci"
            ]
          },
          "pfNames": [
            "enp67s0f1#8-31",
            "enp68s0f0#8-31"
          ]
        },
        {
          "resourceName": "mlnx_sriov_rdma",
          "isRdma": true,
          "selectors": {
            "vendors": [
              15b3
            ],
            "devices": [
              "1018"
            ],
            "drivers": [
              "mlx5_ib"
            ]
          }
        }
      ]
    }


# -- Tolerations for pod assignment.
tolerations:
  - operator: Exists
    effect: NoSchedule
  - operator: Exists
    effect: NoExecute


affinity: {}
